import Head from "next/head";
import Link from "next/link";
import { Flex } from "@chakra-ui/react";
import Navbar from "../components/navbar/Navbar";
import Sidebar from "../components/navbar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Orbeez | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex minH="100vh" flexDirection="column">
        <Navbar />
        <Sidebar />
      </Flex>
    </>
  );
}
